services:
  mongo:
    image: mongo:5.0.0-focal
    ports:
    - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
  bugtracker:
    image: i50729/bug-tracker:0.0.1-SNAPSHOT
    ports:
      - 9002:9002
    depends_on:
      - mongo
  mongo-express500:
    image: mongo-express:0.54
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
      - ME_CONFIG_MONGODB_SERVER=mongo
    depends_on:
      - mongo