services:
  bug-tracker:
    #image: i50729/bug-tracker:0.0.2-SNAPSHOT
    build: ./bug-tracker
    ports:
      - 9002:9002
    depends_on:
      - mongo
    
  mongo:
    image:
      mongo:7.0.5
    container_name: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: pass
      MONGO_INITDB_DATABASE: mongo
    #volumes:
     # - ./data:/data/db
  
#  mongo-express:
 #   image: mongo-express:1.0.2-20-alpine3.18
  #  ports:
   #   - 8081:8081
    #environment:
     # - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      #- ME_CONFIG_MONGODB_ADMINPASSWORD=pass
      #- ME_CONFIG_MONGODB_SERVER=mongo
    #depends_on:
     # - mongo

#to implement and use Docker secrets for enhanced security
#to remove trivial comments