server:
  port: 9090

spring:
  application:
    name: bug-tracker
  data:
    mongodb:
      #host: localhost # for running bug-tracker app without its container
      host: localhost
      port: 27017
      database: bugsdb
      authentication-database: admin
      username: admin
      password: ${DB_PASSWORD}